проект собран
itwassoclear/Mesto pull request #1
Opened 2020-05-24 09:19 UTC by itwassoclear

- код приложения разбит на модули и связан директивами export и import
- установлен вебпак для работы с изображениями и их оптимизации
- настроены сборки build и dev
- настроен hot reload
- использован env — environment variables
- сайт открывается по ссылке в readme

2020-05-24 18:56 UTC, aarefiev requested changes
Хорошая работа. Выполнено дополнительное задание :+1: .

Есть не все необходимые ветки (есть master и develop, не хватает gh-pages), проект на Github Pages вроде выложен, открывается, функционал на сайте работает. Подключение к API происходит по домену по протоколу HTTPS. README.md есть, оформлено, но нет инструкции о том как развернуть проект и не указана версия. Временные файлы игнорируются. В самой работе используется `webpack`, есть файл `.nojekyll`, настроено хэширование CSS и JS файлов, настроен транспайл JS код в ES5, минификация и проставление префиксов в CSS, оптимизация изображений. Корректность настройки проверить не удалось, бандл не до конца билдится, возникают ошибки при запуске билда. Подключение к API локально проверить не удалось.

Ниже я указал краткий список ошибок и улучшений, которые могут улучшить работу. Развернутые комментарии будут непосредственно в коде.

**Нужно исправить:**
1. Доработать README.md.
2. Ошибка при сборке.

**Можно лучше:**
1. Вынести `targets` в отдельный файл.
2. Указать описание проекта.

2020-05-24 18:56 UTC, aarefiev commented on README.md
> +## Функционал
Нужно исправить: доработать README.md.
Нужно указать в описании:
- версию,
- инструкцию о том как развернуть проект локально

Версия указана в `package.json`. По идее при внесении изменений нужно обновлять версию в `package.json`, в `README.md` и пушить тэг в репозиторий. Как об этом пишут в практике. Главное обратить внимание, что `git tag` по-умолчанию не пушится, нужно либо настраивать конфиг, либо писать `git push --tags`.

Дополнительно скину ресурсы, которые помогут его улучшить:
- статья "[Как написать хороший README?](https://medium.com/astrolabe/%D0%BA%D0%B0%D0%BA-%D0%BD%D0%B0%D0%BF%D0%B8%D1%81%D0%B0%D1%82%D1%8C-%D1%85%D0%BE%D1%80%D0%BE%D1%88%D0%B8%D0%B9-readme-159f88076b26)".
- примеры шаблонов для README:
  - https://gist.github.com/PurpleBooth/109311bb0361f32d87a2,
  - https://gist.github.com/fvcproductions/1bfc2d4aecb01a834b46

2020-05-24 18:56 UTC, aarefiev commented on babel.config.js
> +        },
Можно лучше: вынести `targets` в отдельный файл.
Благодаря использованию https://github.com/browserslist/browserslist можно задать единые параметры поддержки для многих инструментов, таких как: `babel`, `autoprefixer` и другие.

2020-05-24 18:56 UTC, aarefiev commented on package.json
> +  "description": "",
Можно лучше: указать описание проекта.
Написать пару слов о чём проект.

2020-05-24 18:56 UTC, aarefiev commented on src/index.js
> +import {CardList} from "./scripts/Cardlist.js";
Нужно исправить: ошибка при сборке.
```bash
ERROR in ./src/index.js
Module not found: Error: Can't resolve './scripts/Cardlist.js' in '/home/jmi/work/ya-reviews/Mesto/src'
 @ ./src/index.js 11:0-49 65:19-27
```

Приводит к тому, что дизайн не отображается
![image](https://user-images.githubusercontent.com/2168159/82762034-a2212280-9e0f-11ea-988a-949783cf8696.png)

2020-05-25 20:06 UTC, itwassoclear commented on README.md
> +## Функционал
можно я прямо здесь спрошу?) в этой работе не было ничего про версии и тэги, про инструкцию тоже не сказано. это необходимость или правила хорошего тона? @aarefiev

2020-05-26 18:54 UTC, aarefiev commented on README.md
> +## Функционал
Я бы сказал и то и то. Больше правило тона, но иснтрукция всегда нужна, чтобы понять как разворачивать проект.

2020-05-26 19:04 UTC, aarefiev requested changes
Отлично. Удалось собрать бандл локально. Там одна ошибка.

**Нужно исправить:** при запуске с хот-релоадом подключение к `API` происходит по `HTTPS`.

2020-05-26 19:04 UTC, aarefiev commented on src/index.js
> -/*
Нужно исправить: при запуске с хот-релоадом подключение к `API` происходит по `HTTPS`.
По заданию в этом случае должно быть подключение по `HTTP`. А при сборке для публикации - по `HTTPS`.

Чтобы это реализовать, достаточно завязаться на значение `NODE_ENV` ([передаётся вот здесь](https://github.com/itwassoclear/Mesto/blob/5ac9c9ca626c1c2d6cfebc433a198a88054999ac/webpack.config.js#L76)). Подробнее: https://webpack.js.org/plugins/define-plugin/ .

2020-05-26 19:18 UTC, itwassoclear commented on src/index.js
> -/*
@aarefiev простите, а можно сразу все требования, которых нет в тренажёре? чтобы я сразу по всем могла пройтись

2020-05-26 19:19 UTC, aarefiev commented on src/index.js
> -/*
А это все. Возможно, требование в задании практики указано не явно. Если так, то рекомендую по этим моментам сделать комментарий в поддержку.

2020-05-27 07:03 UTC, aarefiev approved these changes
Отлично. Ошибки исправлены, новых не обнаружено.
Работа принимается :rocket: .

2020-05-27 07:05 UTC, merged